### ISSUE TITLE
justify (raggedright) the content on Abstract page and Acknowledge page

### ISSUE THREAD

**Issue by yishanhe** [yishanhe/WM-AS-thesis-latex-template#1]
**Pro:**
- looks better

**Concerns:**

- Right now the sample page showing left alignment. Not sure justify (raggedright) can pass the format review. Need feedback here.

**Comment by sgoodm** [comment]
As of Fall 2020, the acknowledgement page must be left aligned to pass format review. It also cannot include bullets or anything else that would prevent a 100% left alignment.

**Comment by yishanhe** [comment]
Thanks for the info. Given the update, close this issue.
